create table items (
  id integer primary key generated by DEFAULT as IDENTITY,
  item_name text not null,
  description text not null,
  quantity integer not null,
  unit_type text not null,
  price integer not null,
  user_id integer REFERENCES users(id) on DELETE CASCADE

);